### ISSUE TITLE
excluding folders .git and node_modules

### ISSUE THREAD

**Issue by virgilwashere** [d-koppenhagen/vscode-file-tree-to-text-generator#2]
How do we configure to ignore `**/.git` and `**/node_modules`?

Or even better, have the extension use global `files.exclude`?

```json
"files.exclude": {
  "**/.gitignore": false,
  "**/.git": true,
  "**/node_modules": true,
  // ...
}
```

And other custom folders?
I would create a `Workspace` or `Folder` `settings.json` when I can set custom folders.

**Comment by d-koppenhagen** [comment]
Great idea! When I will find some spare time I will have a look at how it can be implemented.

Feel also free to contribute!

**Comment by virgilwashere** [comment]
Maybe use `findFiles` here

```ts
const beforSortFiles = fs.readdirSync(selectedRootPath);
```

```ts
findFiles(include: GlobPattern, exclude?: GlobPattern | null, maxResults?: number, token?: CancellationToken): Thenable<Uri[]>
```

**Comment by leosdad** [comment]
Please. This is a must. Any news here?

**Comment by d-koppenhagen** [comment]
check out version 1.4.0 🚀

**Comment by ghost** [comment]
Cool! It works.

Now, is it possible to delimit levels of exlcusion?

For example, choosing a depth of 5 for all files but including `node_modules` only in a depth of 1, something like this:

```
"tree-generator.exclude: {
    "node_modules/**/*.*": true
}
```

**Comment by d-koppenhagen** [comment]
Hmm have you checked if this can be solved by the "right" glob pattern?
I use the micromatch package, here are the supported glob patterns: 
https://www.npmjs.com/package/micromatch#matching-features

**Comment by ghost** [comment]
I have tried a few ways I know, but none worked. I am still on it.

**Comment by tarunnsingh** [comment]
```json
"tree-generator.exclude": {
    "/.github/": true,
    ".gitignore": true,
    ".vscode/": true,
    "**/node_modules/": true
  }
```
This dosen't exculde any of the said folders. What is the correct Way?
