### ISSUE TITLE
出现生成的内容为空白情况

### ISSUE THREAD

**Issue by Luyi365** [d-koppenhagen/vscode-file-tree-to-text-generator#9]
有好几次，我在编写项目资料时需要用到这个插件，但发现它生成的内容页面为空白，如下图所示👇
![Snipaste_2024-04-15_09-14-01](https://github.com/d-koppenhagen/vscode-file-tree-to-text-generator/assets/53433857/49a5b625-5de0-46d2-b5ec-ae322b3e3514)  
并不是每次都会这样，但我也遇到了好几次这样的情况。
希望能尽快修复，因为这个问题我不得不暂时先使用其他插件来代替使用。

**Comment by d-koppenhagen** [comment]
Sorry, please in English.
